language: python
python:
  - "3.8"
#  - "3.8-dev"  # 3.8 development branch 
# command to install dependencies
install:
  - pip install coverage
# command to run tests
script: 
  - coverage run -m test_postinumerot.py
after_success: 
  - coverage report -m